### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by altoning** [Ironholds/rgeoip#1]
install_github("ironholds/rgeoip") cannot find master.zip

**Comment by Ironholds** [comment]
Could you give the full error, the code you're running to generate it, and the platform?

**Comment by altoning** [comment]
R
> library(devtools)
> install_github("ironholds/rgeoip")
Installing github repo(s) ironholds/rgeoip/master from hadley
Installing ironholds/rgeoip.zip from https://github.com/hadley/ironholds/rgeoip/archive/master.zip
Error: client error: (404) Not Found

**Comment by Ironholds** [comment]
Huh; what version of devtools are you running? It looks like it's assuming Hadley's account as the default, and treating "ironholds" as a repo.

**Comment by altoning** [comment]
Don't know what version but I re-installed it using install.packages('devtools') but same error.

**Comment by Ironholds** [comment]
Paste the output of sessionInfo()?

**Comment by altoning** [comment]
> sessionInfo()
R version 2.15.3 RC (2013-02-22 r62040)
Platform: x86_64-apple-darwin9.8.0/x86_64 (64-bit)

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] devtools_1.1

loaded via a namespace (and not attached):
 [1] digest_0.6.2    evaluate_0.4.3  httr_0.2        memoise_0.1
 [5] parallel_2.15.3 RCurl_1.95-3    stringr_0.6.2   tcltk_2.15.3
 [9] tools_2.15.3    whisker_0.1

**Comment by Ironholds** [comment]
Well, that probably explains it; devtools is ~6 versions out of date, and uses different syntax. Try install_github("ironholds","rgeoip").

**Comment by altoning** [comment]
> install_github("ironholds","rgeoip")
Installing github repo(s) ironholds/master from rgeoip
Installing ironholds.zip from https://github.com/rgeoip/ironholds/archive/master.zip
Error: client error: (404) Not Found

**Comment by Ironholds** [comment]
Ack; wrong way around. install_github("rgeoip","ironholds").

**Comment by altoning** [comment]
Now downloads but I get an error message ...

install_github("rgeoip","ironholds")
Installing github repo(s) rgeoip/master from ironholds
Installing rgeoip.zip from https://github.com/ironholds/rgeoip/archive/master.zip
Installing rgeoip
Error: not compatible with STRSXP

**Comment by altoning** [comment]
Going offline now. I'll be back tonight. Thanks for all the work.

**Comment by Ironholds** [comment]
I have no idea; it may be a platform-dependent bug. I would strongly advocate upgrading to R3, though.

**Comment by altoning** [comment]
Yes. It's probably R3 vs R2. 

Anyway, I just realized I need a R API for GeoIP2-City - not GeoIP2-Country

Thanks for your troubles

**Comment by Ironholds** [comment]
Aha; gotcha!
